import React from 'react'

interface BodyProps {

}

export const Body: React.FC<BodyProps> = ({ }) => {
  const text: String[] = ['Our goal isn’t just to grow our market cap and treasury as large as possible, but to use the treasury effectively in order to constantly develop and incubate new, innovative projects - all owned by the DAO. Magnet DAO will become an on-chain conglomerate, with significant holdings in crypto tokens and multi-faceted projects all under the Magnet DAO umbrella, with the DAO (tokenholders) benefitting from fee streams generated from these projects.', 'In essence, Magnet DAO investors will get exposure to projects at their earliest stages - something typically only accessible to VC’s or Angel Investors; while also benefiting from the extraordinary yield generated by the protocol’s staking / bonding mechanism.'];
  const title: String = 'Magnet DAO is a new, innovative project which implements protocol controlled value and _________________in order to create long-standing value for tokenholders.';
  const text2: String[] = ['$MAG is launching natively on Avalanche (AVAX) and will be available for swapping on Trader Joe. We plan to expand to cross-chain in the future.'];
  const title2: String = 'Magnet DAO ($MAG) is our native governance token which will be used to govern the DAO. The DAO will have voting power for major protocol decisions and treasury management.';

  return (
    <div className='body-container'>
      
      <div className='body-row'>
        <BodyImageLeft />
        <BodyText title={title} text={text} />
      </div>

      <BodyBanner />

      <div className='body-row'>
        <BodyText title={title2} text={text2} />
        <BodyImageRight />
      </div>

    </div>
  )
}

const BodyImageLeft = ({ }) => (
  <div className='body-image body-image-left'>

  </div>
)

const BodyImageRight = ({ }) => (
  <div className='body-image body-image-right'>

  </div>
)

const BodyTitle = ({ text }) => (
  <div className='body-title'>
    {text}
  </div>
)

const BodyText = ({ title, text }) => (
  <div className='body-text-container'>
    <BodyTitle text={title} />
    <div className='body-text'>
      {text[0]}
    </div>
    {text[1] ?
      <div className='body-text'>
        {text[1]}
      </div> : <></>}
  </div>
)

const BodyBanner = ({ }) => (
  <div className='body-banner'>
    <BodyBannerItem title='NAME' text='Magnet DAO' />
    <BodyBannerItem title='SYMBOL' text='MAG' />
    <BodyBannerItem title='CONTRACT' text='TBD' />
    <BodyBannerItem title='CHAIN' text='Avalanche (AVAX)' />
    <BodyBannerItem title='TOTAL SUPPLY' text='1,000,000 MAG' />
  </div>
)

const BodyBannerItem = ({ title, text }) => (
  <div className='body-banner-item'>
    {title}
    <span className='body-banner-item-text'>
      {text}
    </span>
  </div>
)